# Application Configuration
spring:
  application:
    name: employee-management
  
  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    
    # Database Connection Pool Configuration (HikariCP)
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # H2 Console (disabled for production, enabled for development/testing)
  h2:
    console:
      enabled: false
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          lob:
            "[non_contextual_creation]": true
        temp:
          "[use_jdbc_metadata_defaults]": false
        validator:
          "[apply_to_ddl]": false
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    "[com.example.employeemanagement]": INFO
    "[org.springframework.web]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.postgresql]": INFO
    "[com.zaxxer.hikari]": DEBUG
