# Production Environment Configuration
spring:
  application:
    name: employee-management-prod
  
  # Production Database Configuration (PostgreSQL)
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employeedb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    
    # Production HikariCP Configuration
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: EmployeeManagementHikariCP
      leak-detection-threshold: 60000
  
  # H2 Console (disabled for production)
  h2:
    console:
      enabled: false
  
  # JPA/Hibernate Configuration for Production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
        jdbc:
          lob:
            "[non_contextual_creation]": true
          "[batch_size]": 20
        temp:
          "[use_jdbc_metadata_defaults]": false
        validator:
          "[apply_to_ddl]": false
        # Production optimizations
        "[order_inserts]": true
        "[order_updates]": true
        "[batch_versioned_data]": true
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Logging Configuration for Production
logging:
  level:
    "[com.example.employeemanagement]": INFO
    "[org.springframework.web]": WARN
    "[org.hibernate.SQL]": WARN
    "[org.postgresql]": WARN
    "[com.zaxxer.hikari]": WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/employee-management.log
    max-size: 10MB
    max-history: 30
