# Application Configuration
spring:
  application:
    name: employee-management
  
  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    
    # Database Connection Pool Configuration (HikariCP)
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # H2 Console (disabled for production, enabled for development/testing)
  h2:
    console:
      enabled: false
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          lob:
            "[non_contextual_creation]": true
        temp:
          "[use_jdbc_metadata_defaults]": false
        validator:
          "[apply_to_ddl]": false
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
  
  # Kafka Configuration for Local Development
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        "[linger.ms]": 5
    consumer:
      group-id: employee-management-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      properties:
        "[spring.json.trusted.packages]": "com.example.employeemanagement.dto"

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    "[com.example.employeemanagement]": INFO
    "[org.springframework.web]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.postgresql]": INFO
    "[com.zaxxer.hikari]": DEBUG
