# Development Environment Configuration
spring:
  application:
    name: employee-management-dev
  
  # Development Database Configuration (H2 for convenience)
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    
    # HikariCP Configuration for Development
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # H2 Console (enabled for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA/Hibernate Configuration for Development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          lob:
            "[non_contextual_creation]": true
        temp:
          "[use_jdbc_metadata_defaults]": false
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 8080

# Logging Configuration for Development
logging:
  level:
    "[com.example.employeemanagement]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.security]": DEBUG
    root: INFO
